KEY_USER_INPUT = "tok715:user-input"
KEY_SPEECH_SYNTHESIZER_INVOCATION = 'tok715:speech-synthesizer:invocation'
KEY_SPEECH_SYNTHESIZER_WORKING = 'tok715:speech-synthesizer:working'

USER_ID_OWNER = "owner"
USER_GROUP_OWNER = USER_ID_OWNER

USER_ID_TOK715 = "tok715"
USER_GROUP_TOK715 = USER_ID_TOK715
USER_DISPLAY_NAME_TOK715 = "卡妹"
